server:
  port: 8081
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  application:
    name: springconfig
  profiles:
    active: native
test:
  user: chen
eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    metadata-map:
      mys: is
      yo: sdf