
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
server:
  port: 8761
spring:
  application:
    name: eureka-server-app